server {
    listen 8001;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /asr {
        proxy_pass http://whisper-asr:9000;
        proxy_read_timeout 7200s;
        client_max_body_size 500M;
    }

    location /detect-language {
        proxy_pass http://whisper-asr:9000;
        proxy_read_timeout 60s;
        client_max_body_size 500M;
    }
}
